### ISSUE TITLE
Classic theme model list correction

### ISSUE THREAD

**Issue by MikeeUK** [nbrightproject/NBrightBuy#25] opened 2016-03-11 18:54 UTC
The testof for the model list is looking for a type double and so always evaluates as false. I believe that this needs to be evaluated as an int.

i.e. 

 `[<tag type='testof' xpath='genxml/textbox/txtsaleprice' testvalue='0' display='{OFF}' />]`

rather than 

`[<tag type='testof' xpath='genxml/textbox/txtsaleprice' testvalue='0.00' display='{OFF}' />]`

**Comment by leedavi** [comment] 2016-03-12 07:44
Hi,
Have you tested that?  I say this because all doubles are saved on hte XML database in en-US format, so therefore "0.00" would be what should exist on the DB and "0.00" is what needs testing!

N.B. The current template system was designed only as a token replacement system and overtime has grown into a mini programming language, which was never my goal.  For this reason we are moving to a razor based template system for the next release, where this kind of difficultly between languages can be solved easier.

**Closed as completed by leedavi** 2016-03-12 07:44 UTC

**Comment by MikeeUK** [comment] 2016-03-15 21:59
Yes I tested it! If it's irrelevant in a future release then cool but in the testing I did regardless of whether 0 or 0.00 are entered for sale price its being saved in the xml data as an integer I have set my region values to en-gb so possibly that's where the issue lies?

**Comment by leedavi** [comment] 2016-03-16 06:42
OK, thx for the feedback. I think when it's extracted from the XML it does the format, I know I've had a couple of issues with this and had to implement workarounds, maybe those workarounds have not yet found there way into the download release! (Which surprises me a little, I thought that was up to date with all fixes for that template system! I'll do some checking)  But for the next release we're solving this by using razor.
